services:
  scraper:
    build: .
    container_name: outlook_calendar_scraper
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OUTLOOK_URL=${OUTLOOK_URL}
      - TZ=Europe/Warsaw
    volumes:
      - ./data:/outlook_calendar_scraper/data
    shm_size: "2gb"

  web:
    image: nginx:alpine
    container_name: calendar_web
    restart: unless-stopped
    ports:
      - "8282:80"
    volumes:
      - ./data:/usr/share/nginx/html:ro
